// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvQq_3W_GFKNcWssi9_mST9mS3cMFAI7E',
    appId: '1:106316614297:web:7731b1c5fd2d78cd508608',
    messagingSenderId: '106316614297',
    projectId: 'child-vaccination-system',
    authDomain: 'child-vaccination-system.firebaseapp.com',
    storageBucket: 'child-vaccination-system.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj2_JLOhYArMrla4EJekVU1MVEE6wcXfQ',
    appId: '1:106316614297:android:328ef0ac5ab1981b508608',
    messagingSenderId: '106316614297',
    projectId: 'child-vaccination-system',
    storageBucket: 'child-vaccination-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs_wARGzzF3a7sw4se3HE_A09qCOZELBQ',
    appId: '1:106316614297:ios:4d68894015c86f19508608',
    messagingSenderId: '106316614297',
    projectId: 'child-vaccination-system',
    storageBucket: 'child-vaccination-system.appspot.com',
    iosClientId: '106316614297-rcn4lcj4il3bsq1nno1npsl2v3fj47t0.apps.googleusercontent.com',
    iosBundleId: 'com.example.childVaccinationSystem',
  );
}
